POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "root2",
  "name": "root",
  "password": "root"
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "root2",
  "name": "root"
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "1234",
  "name": "root",
  "password": "12"
}