### Log in for token
POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "root",
  "password": "root"
}

### Create a blog
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYyODA3YTM3ZThlZmY2N2EzZDA5Yjg2NyIsImlhdCI6MTY1MjY4NzczN30.zns70Cj6qdfOQi0CyhdKDMI7a7-ujRsKVuZxXdok-ZY

{
  "title": "Hello world",
  "author": "Arnel Bucio",
  "url": "hello-world",
  "likes": 42
}

### Delete blog
DELETE http://localhost:3003/api/blogs/6283067e49984e88c77bb4bf
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYyODA3YTM3ZThlZmY2N2EzZDA5Yjg2NyIsImlhdCI6MTY1MjY4NzczN30.zns70Cj6qdfOQi0CyhdKDMI7a7-ujRsKVuZxXdok-ZY
