POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "root",
  "password": "root"
}


### wrong logins
POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "xroot",
  "password": "root"
}