POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "VS Code Rest client is pretty good",
  "important": false,
  "userId": "627f7bc03ccaf4a42d5d3ea8"
}

### Test validation
POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "lol",
  "important": false,
  "userId": "627f7bc03ccaf4a42d5d3ea8"
}
