POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "VS Code Rest client is pretty good",
  "important": false,
  "userId": "627f7bc03ccaf4a42d5d3ea8"
}

### With auth
POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYyN2Y3YmMwM2NjYWY0YTQyZDVkM2VhOCIsImlhdCI6MTY1MjU4NTExOX0.GP8qHRdf2Dv_piL0CrRB18jJyic2dWJEFwYhqOTcam0

{
  "content": "Single page apps use token auth",
  "important": false,
  "userId": "627f7bc03ccaf4a42d5d3ea8"
}
